### ISSUE TITLE
Does this work on s98 files created with pmd2s98?

### ISSUE THREAD

**Issue by tomas** [digital-sound-antiques/s98-to-vgm#2]
I just tried using s98-to-vgm to convert a s98 file created with [pmd2s98](http://www.vesta.dti.ne.jp/~tsato/soft_s98v3.html), but it sounds awful. Do you know if there is anything specific with these files that needs to be fine-tuned or modified before using your script? 

Thanks in advance!

PS: [This is the original .m2 file and the converted .s98 file](https://github.com/digital-sound-antiques/s98-to-vgm/files/7653986/pmd2s98s.tar.gz).

**Comment by okaxaki** [comment]
I have created .vgm file from your .s98 file but there seems to be no problem. Which player did you use? If you use hardware player, please confirm your player's settings or chip's real clock.

**Comment by tomas** [comment]
I'm using the [muki](https://muki.io) web player, which uses libgme for VGM playback. Which player did you use?

**Comment by okaxaki** [comment]
I uses vgmplay (both command-line and winamp plugin).
 
I tried muki web player and it seems that volume overflow is occured for some OPNA vgm. 
(I checked an OPN vgm (instead of OPNA) created with this tool, it was correctly played on muki).

I also tried to reduce the volume of OPNA sound by using vgm's `volume modifier` but it does not solve the problem. The muki player seems to ignore the modifier.

If possible, please ask the support of muki player.

**Comment by tomas** [comment]
Yes you were right! There was something wrong with the volume calculation in the Muki VGM player (I am the author by the way). Thanks for the prompt response and congrats for your work!

**Comment by okaxaki** [comment]
oh sorry that i did not notice you are the author! thanks!
